version: '3'
services:
  devops:
    image: ramu478/devopsrepo
    ports:
      - "90:80"
    deploy:
      replicas: 3

  aws:
    image: ramu478/awsrepo
    ports:
      - "91:80"
    deploy:
      replicas: 3

  datascience:
    image: ramu478/dsrepo
    ports:
      - "92:80"
    deploy:
      replicas: 3

  azure:
    image: ramu478/azurerepo
    ports:
      - "93:80"
    deploy:
      replicas: 3
